add visibility functions
SquidDev-CC/CC-Tweaked pull request #562
Opened 2020-10-27 15:28 UTC by devomaa

2020-10-27 15:41 UTC, SquidDev requested changes
Thanks for the contribution! I've left a couple of comments of a few wee issues I've noticed.

2020-10-27 15:41 UTC, SquidDev commented on src/main/resources/data/computercraft/lua/rom/apis/window.lua
> +    function window.setVisible(b)
There's already a `setVisible` function on line 467. It's probably worth moving `isVisible` to there too.

https://github.com/SquidDev-CC/CC-Tweaked/blob/61fb4caaad51b83ac4a8a5999e50d439f94c71bf/src/main/resources/data/computercraft/lua/rom/apis/window.lua#L467

2020-10-27 15:41 UTC, SquidDev commented on src/main/resources/data/computercraft/lua/rom/apis/window.lua
> +    function window.isVisible()
Can you add a brief documentation comment too please? See `getPosition` of the sort of thing you need to say.

2020-10-27 15:41 UTC, SquidDev commented on src/test/resources/test-rom/spec/apis/window_spec.lua
> +        it("sets window visibility", function()
I don't think this test is needed, given it's the same as below.

2020-10-27 15:41 UTC, SquidDev commented on src/test/resources/test-rom/spec/apis/window_spec.lua
> +           expect(w.isVisible()):same(true)
I don't think you meant to write `true` here. :thinking:

2020-10-27 17:00 UTC, devomaa reviewed
fixed it :)

2020-10-31 09:55 UTC, closed without merging

2020-10-31 09:56 UTC, SquidDev commented
Ended up merging this manually, sorry! Just had some fixes I wanted to push, and for whatever reason, couldn't update the PR's branch.