Strict Globals
SquidDev-CC/CC-Tweaked pull request #583
Opened 2020-11-17 22:26 UTC by Lupus590

Defaults to off to preserve old behaviour.

2020-11-17 22:46 UTC, Lemmmy commented
Should default on :japanese_goblin:

2020-11-18 09:30 UTC, SquidDev requested changes
I've only [tested this quickly on copy-cat](https://copy-cat.squiddev.cc/gh/pull/583/), but I from what I can tell, it doesn't appear to work.

The trouble is that `os.run` clobbers the metatable, which means that `__newindex` is never used.

https://github.com/SquidDev-CC/CC-Tweaked/blob/d2a1a00dc43e5b65f6b64111ce76dd3db16c919f/src/main/resources/data/computercraft/lua/bios.lua#L520-L525

I think there's two options here:
 - Move this check into `os.run`.
 - Make `os.run` not overwrite the metatable.

Of course, the two are not mutually exclusive, though I am inclined to just go for the first of those. _Technically_ `os.run` is the "correct" way to launch a program (it's what `multishell` etc... do), so I think it makes sense to add it there.

Maybe worth calling it `bios.strict_globals` or something then though?

2020-11-18 09:30 UTC, SquidDev commented on src/main/resources/data/computercraft/lua/bios.lua
> +        type = "boolean",
The indentation is a little odd here.

2020-11-18 20:38 UTC, Lupus590 commented
Now I'm wondering if I could write a program/API that can toggle the behaviour for the current shell.  While I fix the issues what do you think of having such a program before I start implementing it? It could be useful for people who want strict globals but also depend on programs which are incompatible with it.

2020-11-21 11:24 UTC, Lupus590 commented
PR is ready to merge, I'm trying to write a program which will toggle the behaviour for the current shell, but it's increasingly looking like I will have to either make a custom shell to disable it in or make code spaghetti. I did manage to make on which would work without multishell though.

2020-11-21 12:06 UTC, SquidDev commented on src/main/resources/data/computercraft/lua/bios.lua
> +    description = "Prevents assigning variables into a program's enviroment. Make sure you use the local keyword or assign to _G explicitly.",
```suggestion
    description = "Prevents assigning variables into a program's environment. Make sure you use the local keyword or assign to _G explicitly.",
```

Sorry, should have spotted this before.

2020-11-21 12:11 UTC, merged

2020-11-21 12:11 UTC, SquidDev commented
Thank you very much!

> TODO: find a spell checker for VSCode that does Lua strings and comments

Emacs has `flyspell-mode` :p.