Fixed missing argument names in file handle docs
SquidDev-CC/CC-Tweaked pull request #632
Opened 2020-12-27 14:41 UTC by MCJack123

This PR fixes some instances of argument names that are missing from various `@cc.param` docs for the file handles.

2020-12-27 18:02 UTC, SquidDev requested changes
Good catch - I really need to get illuaminate to complain about these, it's happened enough times. 

I think in each case the function only accepts one value, it's just we can accept any value (which our argument system doesn't handle very well). So maybe worth using `val` or `str` instead of `...`?

2020-12-27 18:26 UTC, MCJack123 commented
Ah, I just saw `IArguments` and figured it was a vararg function (I didn't remember it being one before anyway). Fixed.

2020-12-27 19:19 UTC, SquidDev commented
Sorry, but could you also revert the `value` -> `value(s)` change?

2020-12-27 23:37 UTC, MCJack123 commented
Oops, missed that. Fixed.

2020-12-28 07:02 UTC, SquidDev approved these changes

2020-12-28 07:02 UTC, merged

2020-12-28 07:03 UTC, SquidDev commented
Ta very much!