Allowed changing how many spaces a tab is in edit.lua
SquidDev-CC/CC-Tweaked pull request #663
Opened 2021-01-08 14:58 UTC by Pechu317

Added a setting to change how many spaces will be created when you hit tab in the edit program. Default is 2 spaces, as per the Lua style guide.

2021-01-08 15:33 UTC, Pechu317 commented
im really bad at this

2021-01-08 18:01 UTC, SquidDev requested changes
Thank you for your PR!

I'd really recommend making and testing these changes locally before submitting a PR. It helps avoid obvious build problems (syntax errors) as well as giving me some confidence there aren't any bugs in the changes.

In this case, I can spot a couple of small issues:
 - The cursor offset when pressing tab hasn't been changed with the indent, so will _always_ increase by 4.
 - The backspace logic hasn't been touched at all, so that still uses an indent of 4.

2021-01-08 19:12 UTC, LoganDark commented
> Default is 2 spaces, as per the Lua style guide.

No. This has already been changed in CC:T from 2 to 4 spaces. The default should stay 4.

2021-01-08 21:46 UTC, Pechu317 commented
> > Default is 2 spaces, as per the Lua style guide.
> 
> No. This has already been changed in CC:T from 2 to 4 spaces. The default should stay 4.
sorry, i forgot to update that. the default is 4.

2021-01-08 21:49 UTC, Pechu317 commented
ok im gonna start using local things now so that everything will build right B)

2021-01-08 22:04 UTC, Pechu317 commented
oh i forgot the backspace logic lemme go do that

2021-01-08 22:31 UTC, Pechu317 commented
cool everything should be done now

2021-01-08 23:12 UTC, LoganDark commented
Also - I'd recommend caching the indent stuff somewhere, like this:

![image](https://user-images.githubusercontent.com/4723091/104073931-c6c1e300-51c3-11eb-965e-94c95c523337.png)

I haven't opened another PR because I don't want to compete with this one. However, calculating string.rep for a constant that never changes throughout the execution of the program is a little wasteful.

2021-01-08 23:28 UTC, Pechu317 commented
...ok

2021-01-09 18:40 UTC, SquidDev requested changes
Thank you for updating. Sorry, just one other nitpick.

2021-01-09 18:40 UTC, SquidDev commented on src/main/resources/data/computercraft/lua/rom/programs/edit.lua
> +                    if x > indent and string.sub(sLine, x - indent, x - 1) == "    " and not string.sub(sLine, 1, x - 1):find("%S") then
The `"    "` should also be `(" "):rep(indent)`. As @LoganDark says, probably worth hoisting this to the top of the file.

2021-02-07 14:57 UTC, closed without merging